# Generated by Django 3.2.9 on 2021-11-23 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishName', models.CharField(max_length=100)),
                ('dishPrice', models.IntegerField()),
                ('dishResturantName', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Dishes',
            },
        ),
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userWhoOrdered', models.CharField(max_length=100)),
                ('resturantOfOrder', models.CharField(max_length=100)),
                ('dishOrder', models.CharField(max_length=100)),
                ('totalPrice', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'OrderPlaced',
            },
        ),
        migrations.CreateModel(
            name='Resturants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resturantName', models.CharField(max_length=100)),
                ('resturantAddress', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Resturants',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=100)),
                ('userType', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
    ]
