# Generated by Django 3.2.9 on 2021-11-23 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishes',
            options={'verbose_name_plural': 'Dishes'},
        ),
        migrations.AlterModelOptions(
            name='orderplaced',
            options={'verbose_name_plural': 'OrderPlaced'},
        ),
        migrations.AlterModelOptions(
            name='resturants',
            options={'verbose_name_plural': 'Resturants'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Users'},
        ),
    ]
